enableGlobalCache: false

nodeLinker: node-modules

plugins:
  - checksum: f1acc8e1c3a565f30b3d93674d9c2bb9a4aeb4ee3e3b397e952ab436d656365510e226acbb0d31f2f286128c55a7ac5aa330392b82eaaf9d780ed44fa51ad28e
    path: .yarn/plugins/plugin-duplicates-list.cjs
    spec: .yarn/plugins/plugin-duplicates-list.cjs

yarnPath: .yarn/releases/yarn-4.12.0.cjs
